Feature: atmosphere shader
scenerygraphics/scenery pull request #594
Opened 2023-08-16 08:32 UTC by smlpt

Implements a dynamic atmosphere shader, based on the Nishita sky model. The code is ported from https://github.com/wwwtyro/glsl-atmosphere. 
An example can be found in basic/AtmosphereExample.

- [ ] dynamically hand over sun position data via @ShaderProperty
- [ ] Implement key binds for sun position and rotation
- [ ] Synchronize a lamp to the sun position
- [ ] Create a default atmosphere object that can be imported to automatically set up an atmosphere

2024-02-02 13:45 UTC, skalarproduktraum requested changes
Thanks, only some minor stuff left 👍

2024-02-02 13:45 UTC, skalarproduktraum commented on src/main/kotlin/graphics/scenery/PointLight.kt
> +    //TODO Remove this part
Follow this TODO, you must 😁

2024-02-02 13:45 UTC, skalarproduktraum commented on src/main/resources/graphics/scenery/backends/shaders/DeferredLighting.frag
> +    // self-lighting property of a material
Remove

2024-02-02 14:29 UTC, smlpt commented on src/main/resources/graphics/scenery/backends/shaders/DeferredLighting.frag
>  	float Specular = texture(InputDiffuseAlbedo, textureCoord).a;
its consistent in IntelliJ so I'll keep it as is.

2024-02-06 09:20 UTC, smlpt commented on src/main/resources/graphics/scenery/backends/shaders/sunProxy.vert
> +    //viewMatrix[3] = vec4(0.0f, 0.0f, 0.0f, 1.0f);
I will completely remove sunproxy.vert, as it isn't used at all anymore.

2024-02-19 10:54 UTC, skalarproduktraum approved these changes

2024-02-19 10:56 UTC, skalarproduktraum approved these changes
Thanks, @smlpt 👍

2024-02-19 10:57 UTC, merged