GLFWMouseAndKeyHandler: fix #377 in windows every click registers as …
scenerygraphics/scenery pull request #777
Opened 2024-09-12 14:11 UTC by moreApi

…left click and no scrolling. There were a few values in the wrong places.

2024-09-12 14:55 UTC, moreApi commented
button2 and button3 do not map to the correct buttons

2024-09-12 15:38 UTC, moreApi commented
they do now. Also the test that never worked corretly works now like it should ... i hope

2024-09-17 12:11 UTC, skalarproduktraum requested changes
One small change/correction, otherwise it looks good to me 👍 Thanks, @moreApi!

2024-09-17 13:18 UTC, moreApi commented on src/main/kotlin/graphics/scenery/controls/GLFWMouseAndKeyHandler.kt
> +                (yoffset.toFloat()*-scrollSpeedMultiplier).toInt(),
nope, horizontal scrolling is not supported by mouseWheelEvent.Those two parameters are different units which are not really clear and no one seems to use it properly in scenery anyway. So I fill both with something sensible and developes down the line have to fiddle around with the rates anyway

2024-09-24 17:35 UTC, skalarproduktraum approved these changes

2024-09-24 17:35 UTC, merged